default:
  regex: (\.out$)|(\.dribble\.)|(\.err$)|(\.o$)|(\.e$)|(\~$)|(\/#)|(\.log$)|(\/LastGraph)|(\/Roadmaps)|(\/Sequences\/)|(ICORN)|(\/IMAGE)|(\/fasta\/)|(\/(t)?blast.?\/)|(tmp)|(\/temp\/)|(\_2$)|(\.crunch$)|(\.sh$)|(\.pl$)|(\.pm$)|(\.py$)|(\.map$)|(\.sam$)|(\.fastq$)|(\.fastq\.gz$)|(\.out\.gz$)|(\.cigar$)|(\.cigar\.gz$)|(\.tar$)
  exclude: .snapshot
  places_to_search: ['pathdata','helminths']
  user_files_threshold: 100
  user_total_space_threshold_gigabytes: 1.0
  users_to_exclude: ['root', 'pathdb','parkhill']
  admin_email_addresses: ['ap13@sanger.ac.uk']
  email_from_address: path-help@sanger.ac.uk

pathdata:
  root_directory:  /nfs/pathdata/.snapshot/nightly.5/Salmonella/typhimurium/A130
  exclude: snapshot
  regex: (\.out$)|(\.dribble\.)|(\.err$)|(\.o$)|(\.e$)|(\~$)|(\/#)|(\.log$)|(\/LastGraph)|(\/Roadmaps)|(\/Sequences\/)|(ICORN)|(\/IMAGE)|(\/fasta\/)|(\/(t)?blast.?\/)|(tmp)|(\/temp\/)|(\_2$)|(\.crunch$)|(\.sh$)|(\.pl$)|(\.pm$)|(\.py$)|(\.map$)|(\.sam$)|(\.fastq$)|(\.fastq\.gz$)|(\.out\.gz$)|(\.cigar$)|(\.cigar\.gz$)|(\.tar$)
  output_file: /tmp/pathdata_files_for_deletion
  
pathogen002:
  root_directory: /nfs/pathogen002
  output_file: /tmp/pathogen002_files_for_deletion
  
helminths:
  root_directory: /nfs/helminths
  output_file: /tmp/helminths_files_for_deletion