default:
  regex: (\/\d{3,5}_\d+((_[12])?[\#\_]\d+(_[12])?)\.fastq(\.gz)?$)|(\~$)|(\.sam$)
  exclude: .snapshot
  places_to_search: ['pathdata','pathdata2','helminths','helminths02','pathogen','pathogen002','pathogen003','pathogen004','pathogen005']
  user_files_threshold: 100
  user_total_space_threshold_gigabytes: 10.0
  users_to_exclude: ['root', 'pathdb','parkhill','pathpipe','gd1']
  admin_email_addresses: ['pathdevg@sanger.ac.uk']
  email_from_address: path-help@sanger.ac.uk

pathdata:
  root_directory:  /nfs/pathdata
  exclude: snapshot
  output_file: /nfs/users/nfs_p/pathpipe/tmp/pathdata_files_for_deletion
  
pathdata2:
  root_directory: /nfs/pathdata2
  output_file: /nfs/users/nfs_p/pathpipe/tmp/pathdata2_files_for_deletion
    
pathogen:
  root_directory: /nfs/pathogen
  output_file: /nfs/users/nfs_p/pathpipe/tmp/pathogen_files_for_deletion
  
pathogen002:
  root_directory: /nfs/pathogen002
  output_file: /nfs/users/nfs_p/pathpipe/tmp/pathogen002_files_for_deletion
  
pathogen003:
  root_directory: /nfs/pathogen003
  output_file: /nfs/users/nfs_p/pathpipe/tmp/pathogen003_files_for_deletion
  
pathogen004:
  root_directory: /nfs/pathogen004
  output_file: /nfs/users/nfs_p/pathpipe/tmp/pathogen004_files_for_deletion
  
pathogen005:
  root_directory: /nfs/pathogen005
  output_file: /nfs/users/nfs_p/pathpipe/tmp/pathogen005_files_for_deletion
  
helminths:
  root_directory: /nfs/helminths
  output_file: /nfs/users/nfs_p/pathpipe/tmp/helminths_files_for_deletion
  
helminths02:
  root_directory: /nfs/helminths02
  output_file: /nfs/users/nfs_p/pathpipe/tmp/helminths02_files_for_deletion
